/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImportRouteImport } from './routes/import'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShelfRouteImport } from './routes/shelf'
import { Route as ClipIdRouteImport } from './routes/clip.$id'
import { Route as LessonIdRouteImport } from './routes/lesson.$id'
import { Route as PracticeIdRouteImport } from './routes/practice.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShelfRoute = ShelfRouteImport.update({
  id: '/shelf',
  path: '/shelf',
  getParentRoute: () => rootRouteImport,
} as any)
const ClipIdRoute = ClipIdRouteImport.update({
  id: '/clip/$id',
  path: '/clip/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonIdRoute = LessonIdRouteImport.update({
  id: '/lesson/$id',
  path: '/lesson/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeIdRoute = PracticeIdRouteImport.update({
  id: '/practice/$id',
  path: '/practice/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/progress': typeof ProgressRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/shelf': typeof ShelfRoute
  '/clip/$id': typeof ClipIdRoute
  '/lesson/$id': typeof LessonIdRoute
  '/practice/$id': typeof PracticeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/progress': typeof ProgressRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/shelf': typeof ShelfRoute
  '/clip/$id': typeof ClipIdRoute
  '/lesson/$id': typeof LessonIdRoute
  '/practice/$id': typeof PracticeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/progress': typeof ProgressRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/shelf': typeof ShelfRoute
  '/clip/$id': typeof ClipIdRoute
  '/lesson/$id': typeof LessonIdRoute
  '/practice/$id': typeof PracticeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/import'
    | '/progress'
    | '/review'
    | '/settings'
    | '/shelf'
    | '/clip/$id'
    | '/lesson/$id'
    | '/practice/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/import'
    | '/progress'
    | '/review'
    | '/settings'
    | '/shelf'
    | '/clip/$id'
    | '/lesson/$id'
    | '/practice/$id'
  id:
    | '__root__'
    | '/'
    | '/import'
    | '/progress'
    | '/review'
    | '/settings'
    | '/shelf'
    | '/clip/$id'
    | '/lesson/$id'
    | '/practice/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImportRoute: typeof ImportRoute
  ProgressRoute: typeof ProgressRoute
  ReviewRoute: typeof ReviewRoute
  SettingsRoute: typeof SettingsRoute
  ShelfRoute: typeof ShelfRoute
  ClipIdRoute: typeof ClipIdRoute
  LessonIdRoute: typeof LessonIdRoute
  PracticeIdRoute: typeof PracticeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shelf': {
      id: '/shelf'
      path: '/shelf'
      fullPath: '/shelf'
      preLoaderRoute: typeof ShelfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clip/$id': {
      id: '/clip/$id'
      path: '/clip/$id'
      fullPath: '/clip/$id'
      preLoaderRoute: typeof ClipIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$id': {
      id: '/lesson/$id'
      path: '/lesson/$id'
      fullPath: '/lesson/$id'
      preLoaderRoute: typeof LessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$id': {
      id: '/practice/$id'
      path: '/practice/$id'
      fullPath: '/practice/$id'
      preLoaderRoute: typeof PracticeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImportRoute: ImportRoute,
  ProgressRoute: ProgressRoute,
  ReviewRoute: ReviewRoute,
  SettingsRoute: SettingsRoute,
  ShelfRoute: ShelfRoute,
  ClipIdRoute: ClipIdRoute,
  LessonIdRoute: LessonIdRoute,
  PracticeIdRoute: PracticeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
